apiVersion: v1
data:
  default.conf: |
    server {
       listen 80;
       index index.php index.html;
       root /var/www/public;
       access_log /var/log/nginx/access.log;
       error_log /var/log/nginx/error.log;
       location / {
        try_files $uri /index.php?$args;
        }
        location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass localhost:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        }
    }
kind: ConfigMap
metadata:
  name: nginx-config-map
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr.deployment
  labels:
    app: hr-web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hr-web
  template:
    metadata:
      labels:
        app: hr-web
    spec:
      containers:
        - name: hr-app
          image: yanar/hr_app:5
        - name: hr-web
          image: yanar/hr_web:3
          volumeMounts:
            - mountPath: /etc/nginx/conf.d/
              name: config
      volumes:
        - name: config
          configMap:
            name: nginx-config-map
            items:
              - key: default.conf
                path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  selector:
    app: hr-web
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30036
      protocol: TCP
