apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-app.deployment
  labels:
    app: hr-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hr-app
  template:
    metadata:
      labels:
        app: hr-app
    spec:
      containers:
        - name: hr-app
          image: yanar/hr_app:5
---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  type: ClusterIP
  selector:
    app: hr-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000